-- Drop the existing tables to start fresh
DROP TABLE IF EXISTS tourist_places;
DROP TABLE IF EXISTS user_itineraries;

-- Tourist Places Table with a 'type' column
CREATE TABLE IF NOT EXISTS tourist_places (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    state TEXT NOT NULL,
    description TEXT,
    budget TEXT,
    safety_level TEXT,
    population_crowd TEXT,
    image_url TEXT,
    type TEXT
);

-- User Itineraries Table
CREATE TABLE IF NOT EXISTS user_itineraries (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    start_date TEXT,
    end_date TEXT,
    itinerary_data TEXT,
    status TEXT
);

INSERT INTO tourist_places (name, state, description, budget, safety_level, population_crowd, image_url, type) VALUES
('Aihole', 'Karnataka', 'Known as the "Cradle of Indian architecture," it contains temples from the 5th to 12th century.', 'Low', 'High', 'Low', './images/destinations/placeholder.jpg', 'Historical'),
('Ajanta Caves', 'Maharashtra', 'A series of rock-cut Buddhist cave monuments that date from the 2nd century BCE to about 480 CE, with intricate paintings and sculptures.', 'Medium', 'High', 'Low', './images/destinations/placeholder.jpg', 'Historical'),
('Alleppey Backwaters', 'Kerala', 'A network of tranquil canals, lakes, and rivers, best explored via a houseboat.', 'Medium', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Natural'),
('Amer Fort', 'Rajasthan', 'Located high on a hill, it is the principal tourist attraction in the Jaipur area, known for its artistic Hindu style elements.', 'Medium', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Historical'),
('Amarnath Temple', 'Jammu and Kashmir', 'A cave shrine located in the Himalayas, famous for a natural ice stalagmite that is a physical manifestation of Lord Shiva.', 'High', 'Low', 'Low', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Andaman Islands', 'Andaman and Nicobar Islands', 'A group of islands with pristine beaches, coral reefs, and dense rainforests, perfect for diving and snorkeling.', 'High', 'High', 'Low', './images/destinations/placeholder.jpg', 'Adventure'),
('Badrinath Temple', 'Uttarakhand', 'A holy shrine dedicated to Lord Vishnu, located in the Chamoli district, part of the Char Dham pilgrimage.', 'High', 'Medium', 'Medium', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Badami Cave Temples', 'Karnataka', 'A complex of four cave temples carved out of sandstone, dating back to the 6th century.', 'Low', 'High', 'Low', './images/destinations/placeholder.jpg', 'Historical'),
('Badami Fort', 'Karnataka', 'A fort complex with historic monuments and beautiful rock carvings.', 'Low', 'High', 'Low', './images/destinations/placeholder.jpg', 'Historical'),
('Chadar Trek', 'Ladakh', 'A famous winter trek on the frozen Zanskar River, known for its challenging terrain and stunning views.', 'High', 'Low', 'Low', './images/destinations/placeholder.jpg', 'Adventure'),
('Charminar', 'Telangana', 'A monument and mosque in Hyderabad, a global symbol of the city, known for its intricate architectural design.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Historical'),
('Cherrapunji', 'Meghalaya', 'Known as one of the wettest places on Earth, famous for its living root bridges and stunning waterfalls.', 'Medium', 'High', 'Low', './images/destinations/placeholder.jpg', 'Adventure'),
('Chittorgarh Fort', 'Rajasthan', 'One of the largest forts in India, a UNESCO World Heritage Site that embodies the valor of Rajputana.', 'Medium', 'High', 'Low', './images/destinations/placeholder.jpg', 'Historical'),
('City Palace, Jaipur', 'Rajasthan', 'A magnificent palace complex in Jaipur, blending Rajasthani and Mughal architecture, housing museums and grand courtyards.', 'Medium', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Historical'),
('Coorg', 'Karnataka', 'A popular coffee-producing hill station, known for its scenic landscapes, waterfalls, and lush greenery.', 'Medium', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Natural'),
('Darjeeling', 'West Bengal', 'A charming hill station in the Himalayas, famous for its tea plantations, stunning views of Mount Kanchenjunga, and the Toy Train.', 'Medium', 'High', 'High', './images/destinations/placeholder.jpg', 'Natural'),
('Dudhwa National Park', 'Uttar Pradesh', 'A national park and tiger reserve in the Terai belt of Uttar Pradesh, home to a diverse variety of wildlife.', 'Medium', 'High', 'Low', './images/destinations/placeholder.jpg', 'Natural'),
('Dudhsagar Falls', 'Goa', 'A magnificent four-tiered waterfall on the Mandovi River, accessible by a thrilling jeep safari.', 'Low', 'Medium', 'High', './images/destinations/placeholder.jpg', 'Adventure'),
('Dwarkadhish Temple', 'Gujarat', 'A revered Hindu temple dedicated to Lord Krishna, believed to be the kingdom of the deity.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Elephanta Caves', 'Maharashtra', 'A collection of cave temples predominantly dedicated to the Hindu god Shiva, located on Elephanta Island near Mumbai.', 'Low', 'High', 'Low', './images/destinations/placeholder.jpg', 'Historical'),
('Ellora Caves', 'Maharashtra', 'A UNESCO World Heritage site known for its monumental rock-cut cave temples and monasteries representing Hinduism, Buddhism, and Jainism.', 'Medium', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Historical'),
('Fatehpur Sikri', 'Uttar Pradesh', 'A historic city built by Mughal Emperor Akbar, featuring the famous Buland Darwaza and Jama Masjid.', 'Medium', 'High', 'Low', './images/destinations/placeholder.jpg', 'Historical'),
('Ganges River', 'Uttar Pradesh', 'A sacred river in Hinduism, revered as a living goddess. The ghats of Varanasi are a key pilgrimage site.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Gangotri', 'Uttarakhand', 'The origin of the holy Ganges River, a revered pilgrimage site in the Garhwal Himalayas.', 'High', 'Medium', 'Low', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Gateway of India', 'Maharashtra', 'The Gateway of India is an arch monument built in the early 20th century in the city of Mumbai.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Historical'),
('Goa', 'Goa', 'Known for its beautiful beaches, vibrant nightlife, and a unique blend of Indian and Portuguese culture.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Adventure'),
('Gokarna', 'Karnataka', 'A small temple town known for its spiritual significance and a series of serene beaches like Om Beach and Kudle Beach.', 'Low', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Natural'),
('Golden Temple, Amritsar', 'Punjab', 'The holiest gurdwara of Sikhism, revered by Hindus, a magnificent golden structure in the heart of a sacred lake.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Golconda Fort', 'Telangana', 'A fortified citadel in Hyderabad, once the capital of the Qutb Shahi dynasty, known for its unique acoustics.', 'Low', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Historical'),
('Gwalior Fort', 'Madhya Pradesh', 'A hill fort near Gwalior, it has been the site of important battles and is famous for its intricate architecture.', 'Medium', 'High', 'Low', './images/destinations/placeholder.jpg', 'Historical'),
('Hampi', 'Karnataka', 'A UNESCO World Heritage Site with a collection of ancient temples, monuments, and ruins of the Vijayanagara Empire.', 'Medium', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Historical'),
('Hampi Bazar', 'Karnataka', 'A historical street market near the Virupaksha Temple ruins, known for its vibrant local culture.', 'Low', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Historical'),
('Haridwar', 'Uttarakhand', 'One of the seven holiest places to Hindus, famous for the daily Ganga Aarti ceremony at Har Ki Pauri.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Hawa Mahal', 'Rajasthan', 'The Palace of Winds, or Hawa Mahal, is a palace in Jaipur, India. It is constructed of red and pink sandstone.', 'Low', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Historical'),
('Humayun''s Tomb', 'Delhi', 'The tomb of the Mughal Emperor Humayun in Delhi. The tomb was commissioned by Humayun''s first wife and chief consort, Empress Bega Begum, in 1569-70.', 'Low', 'High', 'Low', './images/destinations/placeholder.jpg', 'Historical'),
('India Gate', 'Delhi', 'A war memorial located astride the Rajpath, dedicated to soldiers of the British Indian Army.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Historical'),
('Jaisalmer Fort', 'Rajasthan', 'One of the largest fully preserved fortified cities in the world, a "living fort" with shops, hotels, and houses inside.', 'Medium', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Historical'),
('Jallianwala Bagh', 'Punjab', 'A historic garden and memorial of national importance in Amritsar, preserved in the memory of those killed in the 1919 massacre.', 'Low', 'High', 'Low', './images/destinations/placeholder.jpg', 'Historical'),
('Jantar Mantar, Delhi', 'Delhi', 'An astronomical observatory built in the 18th century, with 13 architectural astronomy instruments.', 'Low', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Historical'),
('Jim Corbett National Park', 'Uttarakhand', 'India''s oldest national park, known for its diverse wildlife, including Bengal tigers, leopards, and elephants.', 'Medium', 'High', 'Low', './images/destinations/placeholder.jpg', 'Natural'),
('Kailash Mansarovar', 'Tibet', 'A sacred mountain and lake in the Himalayas, revered by Hindus as the abode of Lord Shiva.', 'High', 'Low', 'Low', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Kamakhya Temple', 'Assam', 'A significant Hindu temple dedicated to the goddess Kamakhya, located on the Nilachal Hill in Guwahati.', 'Low', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Kashi Vishwanath Temple', 'Uttar Pradesh', 'One of the most famous Hindu temples dedicated to Lord Shiva, located on the western bank of the Ganges.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Kaziranga National Park', 'Assam', 'A UNESCO World Heritage Site and home to the world''s largest population of one-horned rhinoceroses.', 'High', 'High', 'Low', './images/destinations/placeholder.jpg', 'Natural'),
('Khajuraho Group of Monuments', 'Madhya Pradesh', 'A UNESCO World Heritage Site known for its temples famous for their intricate erotic sculptures.', 'Medium', 'High', 'Low', './images/destinations/placeholder.jpg', 'Historical'),
('Kodaikanal', 'Tamil Nadu', 'A tranquil hill station known as the "Princess of Hill Stations," famous for its beautiful forests and lake.', 'Low', 'High', 'Low', './images/destinations/placeholder.jpg', 'Natural'),
('Konark Sun Temple', 'Odisha', 'A 13th-century temple shaped like a giant chariot, a UNESCO World Heritage Site dedicated to the Sun God.', 'Low', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Kullu', 'Himachal Pradesh', 'A popular tourist valley and a hub for adventure sports like trekking, rafting, and paragliding.', 'Medium', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Natural'),
('Lonavala', 'Maharashtra', 'A hill station near Pune and Mumbai, famous for its scenic beauty, waterfalls, and caves.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Natural'),
('Madurai', 'Tamil Nadu', 'One of the oldest continuously inhabited cities in the world, home to the Meenakshi Amman Temple.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Historical'),
('Magnetic Hill', 'Ladakh', 'A famous gravity hill where vehicles appear to move upwards against the gravitational force.', 'Medium', 'High', 'Low', './images/destinations/placeholder.jpg', 'Natural'),
('Mahabaleshwar', 'Maharashtra', 'A beautiful hill station in the Western Ghats, famous for its picturesque viewpoints, strawberry farms, and cool climate.', 'Low', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Natural'),
('Mahabalipuram', 'Tamil Nadu', 'A UNESCO World Heritage Site known for its 7th and 8th-century rock-cut temples, mandapas, and shore temples.', 'Low', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Historical'),
('Mahabodhi Temple', 'Bihar', 'A UNESCO World Heritage Site and one of the most sacred places in Buddhism, also revered by Hindus.', 'Low', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Manali', 'Himachal Pradesh', 'A high-altitude resort town in the Himalayas, famous for its snowy peaks, valleys, and vibrant culture.', 'Medium', 'High', 'High', './images/destinations/placeholder.jpg', 'Natural'),
('Marine Drive', 'Maharashtra', 'A 3.6-kilometer-long boulevard in Mumbai, known as the Queen''s Necklace, offering stunning views of the Arabian Sea.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Natural'),
('Meenakshi Amman Temple', 'Tamil Nadu', 'A historic Hindu temple in Madurai, dedicated to Goddess Meenakshi. A masterpiece of Dravidian architecture.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Mehrangarh Fort', 'Rajasthan', 'One of the largest and most magnificent forts in India, located on a hill in Jodhpur, offering panoramic city views.', 'Low', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Historical'),
('Munnar', 'Kerala', 'A hill station in the Idukki district, known for its extensive tea plantations, winding lanes, and misty mountains.', 'Medium', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Natural'),
('Mussoorie', 'Uttarakhand', 'A popular hill station in the Himalayan foothills, known for its scenic beauty, waterfalls, and colonial charm.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Natural'),
('Mysore Palace', 'Karnataka', 'The historical palace and a royal residence at Mysore in the Indian State of Karnataka.', 'Medium', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Historical'),
('Nainital', 'Uttarakhand', 'A popular hill station in Uttarakhand, known for its serene lake, picturesque views, and colonial buildings.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Natural'),
('Nanda Devi National Park', 'Uttarakhand', 'A UNESCO World Heritage Site known for its scenic beauty, alpine meadows, and diverse wildlife.', 'High', 'Low', 'Low', './images/destinations/placeholder.jpg', 'Adventure'),
('Nilgiri Hills', 'Tamil Nadu', 'A mountain range in the Western Ghats, home to Ooty and Coonoor, known for its tea plantations and scenic beauty.', 'Medium', 'High', 'High', './images/destinations/placeholder.jpg', 'Natural'),
('Ooty', 'Tamil Nadu', 'A charming hill station known as the "Queen of Hill Stations," famous for its beautiful botanical gardens, lakes, and misty mountains.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Natural'),
('Palolem Beach', 'Goa', 'A serene, crescent-shaped beach known for its tranquil waters and lively hut-lined shores, perfect for a relaxing getaway.', 'Low', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Natural'),
('Pangong Tso Lake', 'Ladakh', 'A spectacular high-altitude lake whose color changes from blue to green to red, made famous by the movie 3 Idiots.', 'High', 'Medium', 'Low', './images/destinations/placeholder.jpg', 'Natural'),
('Pattadakal', 'Karnataka', 'A UNESCO World Heritage Site known for its complex of 7th and 8th-century Hindu and Jain temples.', 'Low', 'High', 'Low', './images/destinations/placeholder.jpg', 'Historical'),
('Periyar National Park', 'Kerala', 'Known for its elephant and tiger reserves, this park offers boat safaris on a scenic lake and is a haven for wildlife.', 'Medium', 'High', 'Low', './images/destinations/placeholder.jpg', 'Natural'),
('Puri Jagannath Temple', 'Odisha', 'An important Hindu temple dedicated to Jagannath, a form of Lord Vishnu, famous for its annual Rath Yatra festival.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Qutub Minar', 'Delhi', 'A minaret and "victory tower" that forms part of the Qutb complex, a UNESCO World Heritage Site in the Mehrauli area of Delhi, India.', 'Low', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Historical'),
('Rann of Kutch', 'Gujarat', 'A vast salt marsh in the Thar Desert, famous for its white, salty landscape and the Rann Utsav festival.', 'Medium', 'High', 'Low', './images/destinations/placeholder.jpg', 'Natural'),
('Rameshwaram', 'Tamil Nadu', 'A sacred pilgrimage site for both Shaivites and Vaishnavites, with a famous temple and beautiful beaches.', 'Low', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Red Fort', 'Delhi', 'A historic fort in the city of Delhi, serving as the main residence of the Mughal Emperors for nearly 200 years.', 'Low', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Historical'),
('Rishikesh', 'Uttarakhand', 'A sacred city on the Ganges river, known as the "Yoga Capital of the World" and a hub for adventure sports.', 'Medium', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Rohtang Pass', 'Himachal Pradesh', 'A high mountain pass on the eastern Pir Panjal Range, popular for its beautiful snow-covered landscapes.', 'Medium', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Adventure'),
('Sabarimala', 'Kerala', 'A major Hindu pilgrimage site in Kerala, dedicated to Lord Ayyappan, located on a hilltop in a dense forest.', 'Medium', 'High', 'Low', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Sanchi Stupa', 'Madhya Pradesh', 'A Buddhist complex famous for its Great Stupa, one of the oldest stone structures in India.', 'Low', 'High', 'Low', './images/destinations/placeholder.jpg', 'Historical'),
('Shaniwar Wada', 'Maharashtra', 'A historic fort in Pune, once the seat of the Peshwas of the Maratha Empire, known for its majestic architecture.', 'Low', 'High', 'Low', './images/destinations/placeholder.jpg', 'Historical'),
('Shirdi Sai Baba Temple', 'Maharashtra', 'A famous temple dedicated to the revered saint Sai Baba of Shirdi, a highly popular pilgrimage site.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Sikkim', 'Sikkim', 'A state in northeastern India, known for its spectacular mountain landscapes and trekking routes.', 'High', 'High', 'Low', './images/destinations/placeholder.jpg', 'Adventure'),
('Spiti Valley', 'Himachal Pradesh', 'A remote valley in the Himalayas, known for its breathtaking landscapes, cold desert, and ancient monasteries.', 'High', 'Low', 'Low', './images/destinations/placeholder.jpg', 'Adventure'),
('Sunderbans National Park', 'West Bengal', 'A large mangrove forest and a biosphere reserve, home to the Royal Bengal Tiger and a wide variety of bird species.', 'High', 'Medium', 'Low', './images/destinations/placeholder.jpg', 'Natural'),
('Taj Mahal', 'Uttar Pradesh', 'An immense mausoleum of white marble, built in Agra by order of the Mughal emperor Shah Jahan in memory of his favourite wife, Mumtaz Mahal. While a masterpiece of Mughal architecture, it is also a popular pilgrimage site for many.', 'Medium', 'High', 'High', './images/destinations/placeholder.jpg', 'Historical'),
('Tawang Monastery', 'Arunachal Pradesh', 'The largest monastery in India, located in a remote mountainous region, a beautiful and serene place.', 'High', 'High', 'Low', './images/destinations/placeholder.jpg', 'Adventure'),
('Thanjavur', 'Tamil Nadu', 'A city famous for the Brihadishvara Temple and a hub of classical Carnatic music.', 'Low', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Historical'),
('Tirupati Balaji Temple', 'Andhra Pradesh', 'A famous Hindu temple dedicated to Lord Venkateswara, the most visited place of worship in the world.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Udaipur City Palace', 'Rajasthan', 'A royal palace complex situated on the banks of Lake Pichola, known for its intricate carvings and stunning views.', 'Medium', 'High', 'High', './images/destinations/placeholder.jpg', 'Historical'),
('Ujjain Mahakaleshwar Temple', 'Madhya Pradesh', 'One of the twelve Jyotirlinga shrines of Lord Shiva, located on the banks of the Kshipra river.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Valley of Flowers National Park', 'Uttarakhand', 'A vibrant national park known for its meadows of alpine flowers and diverse fauna, a great trek for nature lovers.', 'High', 'Medium', 'Low', './images/destinations/placeholder.jpg', 'Natural'),
('Victoria Memorial', 'West Bengal', 'A large marble building in Kolkata dedicated to Queen Victoria, now a museum under the Ministry of Culture.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Historical'),
('Wagah Border', 'Punjab', 'A ceremonial border post between India and Pakistan known for its daily military parade and flag-lowering ceremony.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Historical'),
('Ziro Valley', 'Arunachal Pradesh', 'A beautiful valley known for its serene environment, pine-clad hills, and the unique culture of the Apatani tribe.', 'High', 'High', 'Low', './images/destinations/placeholder.jpg', 'Adventure'),
('Majuli', 'Assam', 'A large river island in the Brahmaputra River, famous for its unique culture, satras (monasteries), and picturesque landscapes.', 'Medium', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Natural'),
('Aizawl', 'Mizoram', 'The capital city of Mizoram, known for its beautiful hills, rich culture, and scenic beauty.', 'Low', 'High', 'Low', './images/destinations/placeholder.jpg', 'Natural'),
('Lunglei', 'Mizoram', 'A charming town in Mizoram, surrounded by green hills, offering beautiful views and a peaceful environment.', 'Low', 'High', 'Low', './images/destinations/placeholder.jpg', 'Natural'),
('Kohima', 'Nagaland', 'The capital city of Nagaland, known for its serene hills, unique tribal culture, and the World War II cemetery.', 'Medium', 'High', 'Low', './images/destinations/placeholder.jpg', 'Historical'),
('Dimapur', 'Nagaland', 'The largest city in Nagaland, known for its rich history, ancient ruins, and vibrant markets.', 'Low', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Historical'),
('Agartala', 'Tripura', 'The capital city of Tripura, known for its beautiful palaces, lakes, and temples.', 'Low', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Historical'),
('Udaipur (Tripura)', 'Tripura', 'Known as the "City of Temples," it is famous for the Tripura Sundari Temple, one of the 51 Shakti Peethas.', 'Low', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Imphal', 'Manipur', 'The capital city of Manipur, known for its historic sites, beautiful lakes, and a vibrant arts scene.', 'Low', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Historical'),
('Loktak Lake', 'Manipur', 'The largest freshwater lake in Northeast India, famous for its circular floating swamps called phumdis.', 'Medium', 'High', 'Low', './images/destinations/placeholder.jpg', 'Natural'),
('Shillong', 'Meghalaya', 'The capital city of Meghalaya, known as the "Scotland of the East" for its lush green hills and waterfalls.', 'Medium', 'High', 'High', './images/destinations/placeholder.jpg', 'Natural'),
('Pelling', 'Sikkim', 'A picturesque town in West Sikkim, offering stunning views of the Kanchenjunga mountain range.', 'High', 'High', 'Low', './images/destinations/placeholder.jpg', 'Natural'),
('Gangtok', 'Sikkim', 'The capital city of Sikkim, a beautiful hill station known for its monasteries, scenic landscapes, and trekking trails.', 'High', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Natural'),
('Nathu La Pass', 'Sikkim', 'A mountain pass in the Himalayas that connects Sikkim with China''s Tibet Autonomous Region.', 'High', 'Low', 'Low', './images/destinations/placeholder.jpg', 'Adventure'),
('Dzongu', 'Sikkim', 'A protected area in North Sikkim, known for its pristine beauty, dense forests, and the culture of the Lepcha people.', 'High', 'High', 'Low', './images/destinations/placeholder.jpg', 'Adventure'),
('Tirupati Balaji Temple', 'Andhra Pradesh', 'A famous Hindu temple dedicated to Lord Venkateswara, the most visited place of worship in the world.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Kashi Vishwanath Temple', 'Uttar Pradesh', 'One of the most famous Hindu temples dedicated to Lord Shiva, located on the western bank of the Ganges.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Gangotri', 'Uttarakhand', 'The origin of the holy Ganges River, a revered pilgrimage site in the Garhwal Himalayas.', 'High', 'Medium', 'Low', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Vaishno Devi', 'Jammu and Kashmir', 'A pilgrimage to the holy shrine of Mata Vaishno Devi, located in the Trikuta Mountains.', 'Medium', 'High', 'High', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Kamakhya Temple', 'Assam', 'A significant Hindu temple dedicated to the goddess Kamakhya, located on the Nilachal Hill in Guwahati.', 'Low', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Shirdi Sai Baba Temple', 'Maharashtra', 'A famous temple dedicated to the revered saint Sai Baba of Shirdi, a highly popular pilgrimage site.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Ujjain Mahakaleshwar Temple', 'Madhya Pradesh', 'One of the twelve Jyotirlinga shrines of Lord Shiva, located on the banks of the Kshipra river.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Somnath Temple', 'Gujarat', 'The first of the twelve Jyotirlinga shrines of Lord Shiva, located on the western coast of India.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Puri Jagannath Temple', 'Odisha', 'An important Hindu temple dedicated to Jagannath, a form of Lord Vishnu, famous for its annual Rath Yatra festival.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Dwarkadhish Temple', 'Gujarat', 'A revered Hindu temple dedicated to Lord Krishna, believed to be the kingdom of the deity.', 'Low', 'High', 'High', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Ramanathaswamy Temple', 'Tamil Nadu', 'A Hindu temple dedicated to Lord Shiva, located on Rameswaram island, part of the Char Dham pilgrimage.', 'Low', 'High', 'Medium', './images/destinations/placeholder.jpg', 'Pilgrimage'),
('Varanasi', 'Uttar Pradesh', 'Known as the spiritual capital of India, famous for its ghats on the Ganges river and ancient temples.', 'Medium', 'High', 'High', './images/destinations/placeholder.jpg', 'Pilgrimage');