-- Drop the existing tables to start fresh
DROP TABLE IF EXISTS tourist_places;
DROP TABLE IF EXISTS user_itineraries;

-- Tourist Places Table with a 'type' column
CREATE TABLE IF NOT EXISTS tourist_places (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    state TEXT NOT NULL,
    description TEXT,
    budget TEXT,
    safety_level TEXT,
    population_crowd TEXT,
    image_url TEXT,
    type TEXT
);

-- User Itineraries Table
CREATE TABLE IF NOT EXISTS user_itineraries (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    start_date TEXT,
    end_date TEXT TEXT,
    itinerary_data TEXT,
    status TEXT
);

-- Insert 100 Destinations with Consistent Categories and Functional Image Links

INSERT INTO tourist_places (name, state, description, budget, safety_level, population_crowd, image_url, type) VALUES
('Meenakshi Amman Temple', 'Tamil Nadu', 'A historic Hindu temple in Madurai, dedicated to Goddess Meenakshi. A masterpiece of Dravidian architecture.', 'Low', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/9/99/Meenakshi_Amman_Temple_Entrance_Sculpture.JPG', 'Pilgrimage'),
('Golden Temple, Amritsar', 'Punjab', 'The holiest gurdwara of Sikhism, revered by Hindus, a magnificent golden structure in the heart of a sacred lake.', 'Low', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/c/ca/Golden_Temple_in_Amritsar.jpg', 'Pilgrimage'),
('Vaishno Devi', 'Jammu and Kashmir', 'A pilgrimage to the holy shrine of Mata Vaishno Devi, located in the Trikuta Mountains.', 'Medium', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/9/99/Vaishno_Devi_Temple.JPG', 'Pilgrimage'),
('Rishikesh', 'Uttarakhand', 'A sacred city on the Ganges river, known as the "Yoga Capital of the World" and a gateway to the Himalayas.', 'Medium', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Rishikesh_Ganges.jpg', 'Pilgrimage'),
('Haridwar', 'Uttarakhand', 'One of the seven holiest places to Hindus, famous for the daily Ganga Aarti ceremony at Har Ki Pauri.', 'Low', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Ganga_Aarti_at_Haridwar_2016.jpg', 'Pilgrimage'),
('Kedarnath Temple', 'Uttarakhand', 'An ancient Hindu temple dedicated to Lord Shiva, located in the Garhwal Himalayan range.', 'High', 'Medium', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Kedarnath_Temple_at_Uttarakhand.jpg', 'Pilgrimage'),
('Badrinath Temple', 'Uttarakhand', 'A holy shrine dedicated to Lord Vishnu, located in the Chamoli district, part of the Char Dham pilgrimage.', 'High', 'Medium', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Badrinath_Temple_Chamoli_district_Uttarakhand.jpg', 'Pilgrimage'),
('Dwarkadhish Temple', 'Gujarat', 'A revered Hindu temple dedicated to Lord Krishna, believed to be the kingdom of the deity.', 'Low', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/b/b3/Dwarkadhish_Temple_Dwarka.jpg', 'Pilgrimage'),
('Somnath Temple', 'Gujarat', 'The first of the twelve Jyotirlinga shrines of Lord Shiva, located on the western coast of India.', 'Low', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/7/77/Somnath_Temple_Gujarat.JPG', 'Pilgrimage'),
('Tirumala Venkateswara Temple', 'Andhra Pradesh', 'A famous Hindu temple dedicated to Lord Venkateswara, located on the Tirumala hills.', 'Low', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Tirumala_Venkateswara_Temple.jpg', 'Pilgrimage'),
('Varanasi', 'Uttar Pradesh', 'Known as the spiritual capital of India, famous for its ghats on the Ganges river and ancient temples.', 'Medium', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Varanasi_Ghats_at_Sunset.jpg', 'Pilgrimage'),
('Puri Jagannath Temple', 'Odisha', 'An important Hindu temple dedicated to Jagannath, a form of Lord Vishnu, famous for its annual Rath Yatra festival.', 'Low', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Puri_Jagannath_Temple_Odisha.jpg', 'Pilgrimage'),
('Rameshwaram', 'Tamil Nadu', 'A sacred pilgrimage site for both Shaivites and Vaishnavites, with a famous temple and beautiful beaches.', 'Low', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Rameshwaram_Temple_Tamil_Nadu.jpg', 'Pilgrimage'),
('Sabarimala', 'Kerala', 'A major Hindu pilgrimage site in Kerala, dedicated to Lord Ayyappan, located on a hilltop in a dense forest.', 'Medium', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/6/67/Sabarimala_Temple.jpg', 'Pilgrimage'),
('Konark Sun Temple', 'Odisha', 'A 13th-century temple shaped like a giant chariot, a UNESCO World Heritage Site dedicated to the Sun God.', 'Low', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/9/90/Konark_Sun_Temple_Odisha.jpg', 'Pilgrimage'),
('Mahabodhi Temple', 'Bihar', 'A UNESCO World Heritage Site and one of the most sacred places in Buddhism, also revered by Hindus.', 'Low', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/3/30/Mahabodhi_Temple_Bodh_Gaya.jpg', 'Pilgrimage'),
('Gangotri', 'Uttarakhand', 'The origin of the holy Ganges River, a revered pilgrimage site in the Garhwal Himalayas.', 'High', 'Medium', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/a/ab/Gangotri_Glacier_Uttarakhand.jpg', 'Pilgrimage'),
('Yamunotri', 'Uttarakhand', 'The source of the Yamuna River, located in the Uttarkashi district of Uttarakhand.', 'High', 'Medium', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/8/87/Yamunotri_Temple_Uttarakhand.jpg', 'Pilgrimage'),
('Kailash Mansarovar', 'Tibet', 'A sacred mountain and lake in the Himalayas, revered by Hindus as the abode of Lord Shiva.', 'High', 'Low', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Mount_Kailash_Tibet.jpg', 'Pilgrimage'),
('Amarnath Temple', 'Jammu and Kashmir', 'A cave shrine located in the Himalayas, famous for a natural ice stalagmite that is a physical manifestation of Lord Shiva.', 'High', 'Low', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Amarnath_Cave_Jammu_and_Kashmir.jpg', 'Pilgrimage'),
('Shirdi Sai Baba Temple', 'Maharashtra', 'A famous temple dedicated to the revered saint Sai Baba of Shirdi, a highly popular pilgrimage site.', 'Low', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/b/b2/Shirdi_Sai_Baba_Temple_Maharashtra.jpg', 'Pilgrimage'),
('Ujjain Mahakaleshwar Temple', 'Madhya Pradesh', 'One of the twelve Jyotirlinga shrines of Lord Shiva, located on the banks of the Kshipra river.', 'Low', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/3/3d/Mahakaleshwar_Jyotirlinga_Temple_in_Ujjain.jpg', 'Pilgrimage'),
('Tirupati Balaji Temple', 'Andhra Pradesh', 'A famous Hindu temple dedicated to Lord Venkateswara, the most visited place of worship in the world.', 'Low', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Tirumala_Venkateswara_Temple.jpg', 'Pilgrimage'),
('Kashi Vishwanath Temple', 'Uttar Pradesh', 'One of the most famous Hindu temples dedicated to Lord Shiva, located on the western bank of the Ganges.', 'Low', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/a/a3/Kashi_Vishwanath_Temple_Varanasi.jpg', 'Pilgrimage'),
('Ramanathaswamy Temple', 'Tamil Nadu', 'A Hindu temple dedicated to Lord Shiva, located on Rameswaram island, part of the Char Dham pilgrimage.', 'Low', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Rameshwaram_Temple_Tamil_Nadu.jpg', 'Pilgrimage');

-- Historical
INSERT INTO tourist_places (name, state, description, budget, safety_level, population_crowd, image_url, type) VALUES
('Taj Mahal', 'Uttar Pradesh', 'An immense mausoleum of white marble...', 'Medium', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/d/da/Taj-Mahal.jpg', 'Historical'),
('Gateway of India', 'Maharashtra', 'The Gateway of India is an arch monument built in the early 20th century in the city of Mumbai.', 'Low', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/1/18/Gateway_of_India_Mumbai_02-2020.jpg', 'Historical'),
('Hawa Mahal', 'Rajasthan', 'The Palace of Winds, or Hawa Mahal, is a palace in Jaipur, India. It is constructed of red and pink sandstone.', 'Low', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/6/6b/Hawa_Mahal_in_Jaipur_India_03-2016_img3.jpg', 'Historical'),
('Qutub Minar', 'Delhi', 'A minaret and "victory tower" that forms part of the Qutb complex, a UNESCO World Heritage Site in the Mehrauli area of Delhi, India.', 'Low', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/3/30/Qutb_Minar_in_New_Delhi_India_03-2016_img5.jpg', 'Historical'),
('Amer Fort', 'Rajasthan', 'Located high on a hill, it is the principal tourist attraction in the Jaipur area, known for its artistic Hindu style elements.', 'Medium', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/d/df/Amer_Fort_Jaipur_India_04-2016_img2.jpg', 'Historical'),
('Red Fort', 'Delhi', 'A historic fort in the city of Delhi, serving as the main residence of the Mughal Emperors for nearly 200 years.', 'Low', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/c/ce/Red_Fort_main_gate.jpg', 'Historical'),
('Humayun''s Tomb', 'Delhi', 'The tomb of the Mughal Emperor Humayun in Delhi. The tomb was commissioned by Humayun''s first wife and chief consort, Empress Bega Begum, in 1569-70.', 'Low', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/3/3f/Humayun_tomb_New_Delhi_India_04-2016_img3.jpg', 'Historical'),
('Mysore Palace', 'Karnataka', 'The historical palace and a royal residence at Mysore in the Indian State of Karnataka.', 'Medium', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Mysore_Palace%2C_India.jpg', 'Historical'),
('Ajanta Caves', 'Maharashtra', 'A series of rock-cut Buddhist cave monuments that date from the 2nd century BCE to about 480 CE, with intricate paintings and sculptures.', 'Medium', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Ajanta_Cave_26_%285%29%2C_Maharashtra%2C_India.jpg', 'Historical'),
('Ellora Caves', 'Maharashtra', 'A UNESCO World Heritage site known for its monumental rock-cut cave temples and monasteries representing Hinduism, Buddhism, and Jainism.', 'Medium', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Ellora_Caves_-_Kailasa_Temple.jpg', 'Historical'),
('Elephanta Caves', 'Maharashtra', 'A collection of cave temples predominantly dedicated to the Hindu god Shiva, located on Elephanta Island near Mumbai.', 'Low', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Elephanta_Caves_-_Cave_1.jpg', 'Historical'),
('Shaniwar Wada', 'Maharashtra', 'A historic fort in Pune, once the seat of the Peshwas of the Maratha Empire, known for its majestic architecture.', 'Low', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/3/30/Shaniwar_Wada_Pune_India_03-2016_img5.jpg', 'Historical'),
('Jallianwala Bagh', 'Punjab', 'A historic garden and memorial of national importance in Amritsar, preserved in the memory of those killed in the 1919 massacre.', 'Low', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Jallianwala_Bagh_Massacre_Memorial.jpg', 'Historical'),
('Wagah Border', 'Punjab', 'A ceremonial border post between India and Pakistan known for its daily military parade and flag-lowering ceremony.', 'Low', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/d/d3/Wagah_border_ceremony%2C_India.jpg', 'Historical'),
('City Palace, Jaipur', 'Rajasthan', 'A magnificent palace complex in Jaipur, blending Rajasthani and Mughal architecture, housing museums and grand courtyards.', 'Medium', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/City_Palace_in_Jaipur_India_04-2016_img1.jpg', 'Historical'),
('Udaipur City Palace', 'Rajasthan', 'A royal palace complex situated on the banks of Lake Pichola, known for its intricate carvings and stunning views.', 'Medium', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/6/6a/Udaipur_City_Palace_%285%29.jpg', 'Historical'),
('Jaisalmer Fort', 'Rajasthan', 'One of the largest fully preserved fortified cities in the world, a "living fort" with shops, hotels, and houses inside.', 'Medium', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/0/05/Jaisalmer_Fort_sunset_view.jpg', 'Historical'),
('Mehrangarh Fort', 'Rajasthan', 'One of the largest and most magnificent forts in India, located on a hill in Jodhpur, offering panoramic city views.', 'Low', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Mehrangarh_Fort_in_Jodhpur_India_03-2016_img1.jpg', 'Historical'),
('Mahabalipuram', 'Tamil Nadu', 'A UNESCO World Heritage Site known for its 7th and 8th-century rock-cut temples, mandapas, and shore temples.', 'Low', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Shore_Temple%2C_Mahabalipuram%2C_Tamil_Nadu%2C_India.jpg', 'Historical'),
('Howrah Bridge', 'West Bengal', 'A massive cantilever bridge over the Hooghly River, connecting Howrah and Kolkata, and a symbol of the city.', 'Low', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Howrah_Bridge_at_night.jpg', 'Historical'),
('Sanchi Stupa', 'Madhya Pradesh', 'A Buddhist complex famous for its Great Stupa, one of the oldest stone structures in India.', 'Low', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Sanchi_Stupa_in_Madhya_Pradesh.jpg', 'Historical'),
('Gwalior Fort', 'Madhya Pradesh', 'A hill fort near Gwalior, it has been the site of important battles and is famous for its intricate architecture.', 'Medium', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Gwalior_Fort_in_Madhya_Pradesh.jpg', 'Historical'),
('Khajuraho Group of Monuments', 'Madhya Pradesh', 'A UNESCO World Heritage Site known for its temples famous for their intricate erotic sculptures.', 'Medium', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/4/47/Khajuraho_Group_of_Monuments.jpg', 'Historical'),
('Fatehpur Sikri', 'Uttar Pradesh', 'A historic city built by Mughal Emperor Akbar, featuring the famous Buland Darwaza and Jama Masjid.', 'Medium', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/d/df/Fatehpur_Sikri_buland_darwaza.jpg', 'Historical'),
('Golconda Fort', 'Telangana', 'A fortified citadel in Hyderabad, once the capital of the Qutb Shahi dynasty, known for its unique acoustics.', 'Low', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/2/22/Golconda_Fort_in_Hyderabad.jpg', 'Historical');

-- Natural
INSERT INTO tourist_places (name, state, description, budget, safety_level, population_crowd, image_url, type) VALUES
('Alleppey Backwaters', 'Kerala', 'A network of tranquil canals, lakes, and rivers, best explored via a houseboat.', 'Medium', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Kuttanadu.jpg', 'Natural'),
('Periyar National Park', 'Kerala', 'Known for its elephant and tiger reserves, this park offers boat safaris on a scenic lake and is a haven for wildlife.', 'Medium', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Periyar_National_Park_%288863152758%29.jpg', 'Natural'),
('Dudhsagar Falls', 'Goa', 'A magnificent four-tiered waterfall on the Mandovi River, accessible by a thrilling jeep safari.', 'Low', 'Medium', 'High', 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Dudhsagar_Falls_During_Monsoon.jpg', 'Natural'),
('Palolem Beach', 'Goa', 'A serene, crescent-shaped beach known for its tranquil waters and lively hut-lined shores, perfect for a relaxing getaway.', 'Low', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/e/ef/Sunset_in_Palolem_Beach_Goa.jpg', 'Natural'),
('Mahabaleshwar', 'Maharashtra', 'A beautiful hill station in the Western Ghats, famous for its picturesque viewpoints, strawberry farms, and cool climate.', 'Low', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/c/c8/Sunrise_point_Mahabaleshwar.jpg', 'Natural'),
('Marine Drive', 'Maharashtra', 'A 3.6-kilometer-long boulevard in Mumbai, known as the Queen''s Necklace, offering stunning views of the Arabian Sea.', 'Low', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Marine_Drive_Mumbai_%283460456184%29.jpg', 'Natural'),
('Jim Corbett National Park', 'Uttarakhand', 'India''s oldest national park, known for its diverse wildlife, including Bengal tigers, leopards, and elephants.', 'Medium', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/e/e4/Jim_Corbett_National_Park_Wildlife.jpg', 'Natural'),
('Valley of Flowers National Park', 'Uttarakhand', 'A vibrant national park known for its meadows of alpine flowers and diverse fauna, a great trek for nature lovers.', 'High', 'Medium', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Valley_of_Flowers_National_Park_Uttarakhand.jpg', 'Natural'),
('Mussoorie', 'Uttarakhand', 'A popular hill station in the Himalayan foothills, known for its scenic beauty, waterfalls, and colonial charm.', 'Low', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/b/b3/Mussoorie_at_night.jpg', 'Natural'),
('Ooty', 'Tamil Nadu', 'A charming hill station known as the "Queen of Hill Stations," famous for its beautiful botanical gardens, lakes, and misty mountains.', 'Low', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/8/87/Ooty_Lake_in_Ooty%2C_Tamil_Nadu.jpg', 'Natural'),
('Coorg', 'Karnataka', 'A popular coffee-producing hill station, known for its scenic landscapes, waterfalls, and lush greenery.', 'Medium', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/9/90/Coorg_Morning.jpg', 'Natural'),
('Gokarna', 'Karnataka', 'A small temple town known for its spiritual significance and a series of serene beaches like Om Beach and Kudle Beach.', 'Low', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/d/df/Gokarna_Beach%2C_Karnataka%2C_India.jpg', 'Natural'),
('Pangong Tso Lake', 'Ladakh', 'A spectacular high-altitude lake whose color changes from blue to green to red, made famous by the movie 3 Idiots.', 'High', 'Medium', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/8/84/Pangong_Tso.jpg', 'Natural'),
('Magnetic Hill', 'Ladakh', 'A famous gravity hill where vehicles appear to move upwards against the gravitational force.', 'Medium', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/f/f0/Magnetic_Hill_Leh_Ladakh.jpg', 'Natural'),
('Darjeeling', 'West Bengal', 'A charming hill station in the Himalayas, famous for its tea plantations, stunning views of Mount Kanchenjunga, and the Toy Train.', 'Medium', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Darjeeling_at_Dusk.jpg', 'Natural'),
('Sunderbans National Park', 'West Bengal', 'A large mangrove forest and a biosphere reserve, home to the Royal Bengal Tiger and a wide variety of bird species.', 'High', 'Medium', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/0/07/Sundarban_Tiger.jpg', 'Natural'),
('Kaziranga National Park', 'Assam', 'A UNESCO World Heritage Site and home to the world''s largest population of one-horned rhinoceroses.', 'High', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/5/5d/One-horned_Rhinoceros_%28Rhinoceros_unicornis%29_at_Kaziranga_National_Park.jpg', 'Natural'),
('Kullu', 'Himachal Pradesh', 'A popular tourist valley and a hub for adventure sports like trekking, rafting, and paragliding.', 'Medium', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Kullu_Valley.jpg', 'Natural'),
('Manali', 'Himachal Pradesh', 'A high-altitude resort town in the Himalayas, famous for its snowy peaks, valleys, and vibrant culture.', 'Medium', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/a/a8/Manali_at_Night.jpg', 'Natural'),
('Rann of Kutch', 'Gujarat', 'A vast salt marsh in the Thar Desert, famous for its white, salty landscape and the Rann Utsav festival.', 'Medium', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Rann_of_Kutch_Sunset.jpg', 'Natural'),
('Kodaikanal', 'Tamil Nadu', 'A tranquil hill station known as the "Princess of Hill Stations," famous for its beautiful forests and lake.', 'Low', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Kodaikanal_Lake_at_Night.jpg', 'Natural'),
('Dudhwa National Park', 'Uttar Pradesh', 'A national park and tiger reserve in the Terai belt of Uttar Pradesh, home to a diverse variety of wildlife.', 'Medium', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Dudhwa_National_Park_Wildlife.jpg', 'Natural'),
('Nainital', 'Uttarakhand', 'A popular hill station in Uttarakhand, known for its serene lake, picturesque views, and colonial buildings.', 'Low', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/3/30/Nainital_Lake.jpg', 'Natural'),
('Lonavala', 'Maharashtra', 'A hill station near Pune and Mumbai, famous for its scenic beauty, waterfalls, and caves.', 'Low', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/d/de/Lonavala_Hill_Station.jpg', 'Natural'),
('Mahabaleshwar', 'Maharashtra', 'A beautiful hill station in the Western Ghats, famous for its picturesque viewpoints, strawberry farms, and cool climate.', 'Low', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/c/c8/Sunrise_point_Mahabaleshwar.jpg', 'Natural');

-- Adventure
INSERT INTO tourist_places (name, state, description, budget, safety_level, population_crowd, image_url, type) VALUES
('Rishikesh', 'Uttarakhand', 'A sacred city on the Ganges river, known as the "Yoga Capital of the World" and a hub for adventure sports.', 'Medium', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Rishikesh_Ganges.jpg', 'Adventure'),
('Jim Corbett National Park', 'Uttarakhand', 'India''s oldest national park, offering diverse wildlife, including Bengal tigers, leopards, and elephants.', 'Medium', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/e/e4/Jim_Corbett_National_Park_Wildlife.jpg', 'Adventure'),
('Valley of Flowers', 'Uttarakhand', 'A vibrant national park known for its meadows of alpine flowers, a popular trek for nature lovers.', 'High', 'Medium', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Valley_of_Flowers_National_Park_Uttarakhand.jpg', 'Adventure'),
('Kullu', 'Himachal Pradesh', 'A popular tourist valley and a hub for adventure sports like trekking, rafting, and paragliding.', 'Medium', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Kullu_Valley.jpg', 'Adventure'),
('Manali', 'Himachal Pradesh', 'A high-altitude resort town in the Himalayas, famous for its snowy peaks, valleys, and vibrant culture.', 'Medium', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/a/a8/Manali_at_Night.jpg', 'Adventure'),
('Gokarna', 'Karnataka', 'A small temple town known for its spiritual significance and a series of serene beaches like Om Beach and Kudle Beach.', 'Low', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/d/df/Gokarna_Beach%2C_Karnataka%2C_India.jpg', 'Adventure'),
('Pangong Tso Lake', 'Ladakh', 'A spectacular high-altitude lake whose color changes from blue to green to red, made famous by the movie 3 Idiots.', 'High', 'Medium', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/8/84/Pangong_Tso.jpg', 'Adventure'),
('Dudhsagar Falls', 'Goa', 'A magnificent four-tiered waterfall on the Mandovi River, accessible by a thrilling jeep safari.', 'Low', 'Medium', 'High', 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Dudhsagar_Falls_During_Monsoon.jpg', 'Adventure'),
('Sunderbans National Park', 'West Bengal', 'A large mangrove forest and a biosphere reserve, home to the Royal Bengal Tiger and a wide variety of bird species.', 'High', 'Medium', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/0/07/Sundarban_Tiger.jpg', 'Adventure'),
('Sikkim', 'Sikkim', 'A state in northeastern India, known for its spectacular mountain landscapes and trekking routes.', 'High', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Sikkim_Himalayas.jpg', 'Adventure'),
('Spiti Valley', 'Himachal Pradesh', 'A remote valley in the Himalayas, known for its breathtaking landscapes, cold desert, and ancient monasteries.', 'High', 'Low', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Spiti_Valley.jpg', 'Adventure'),
('Chadar Trek', 'Ladakh', 'A famous winter trek on the frozen Zanskar River, known for its challenging terrain and stunning views.', 'High', 'Low', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Chadar_Trek_Ladakh.jpg', 'Adventure'),
('Rohtang Pass', 'Himachal Pradesh', 'A high mountain pass on the eastern Pir Panjal Range, popular for its beautiful snow-covered landscapes.', 'Medium', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/b/b9/Rohtang_Pass_in_Himachal_Pradesh.jpg', 'Adventure'),
('Tawang Monastery', 'Arunachal Pradesh', 'The largest monastery in India, located in a remote mountainous region, a beautiful and serene place.', 'High', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Tawang_Monastery.jpg', 'Adventure'),
('Cherrapunji', 'Meghalaya', 'Known as one of the wettest places on Earth, famous for its living root bridges and stunning waterfalls.', 'Medium', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/0/09/Cherrapunji_Meghalaya.jpg', 'Adventure'),
('Andaman Islands', 'Andaman and Nicobar Islands', 'A group of islands with pristine beaches, coral reefs, and dense rainforests, perfect for diving and snorkeling.', 'High', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Andaman_Islands_beach.jpg', 'Adventure'),
('Goa', 'Goa', 'Known for its beautiful beaches, vibrant nightlife, and a unique blend of Indian and Portuguese culture.', 'Low', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Goa_Sunset_Beach.jpg', 'Adventure'),
('Rann of Kutch', 'Gujarat', 'A vast salt marsh in the Thar Desert, famous for its white, salty landscape and the Rann Utsav festival.', 'Medium', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Rann_of_Kutch_Sunset.jpg', 'Adventure'),
('Nanda Devi National Park', 'Uttarakhand', 'A UNESCO World Heritage Site known for its scenic beauty, alpine meadows, and diverse wildlife.', 'High', 'Low', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Nanda_Devi_National_Park_Uttarakhand.jpg', 'Adventure'),
('Valley of Flowers', 'Uttarakhand', 'A vibrant national park known for its meadows of alpine flowers and diverse fauna, a great trek for nature lovers.', 'High', 'Medium', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Valley_of_Flowers_National_Park_Uttarakhand.jpg', 'Adventure'),
('Munnar', 'Kerala', 'A hill station in the Idukki district, known for its extensive tea plantations, winding lanes, and misty mountains.', 'Medium', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/b/be/Munnar_Tea_Plantations.jpg', 'Adventure'),
('Chittorgarh Fort', 'Rajasthan', 'One of the largest forts in India, a UNESCO World Heritage Site that embodies the valor of Rajputana.', 'Medium', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/3/36/Chittorgarh_Fort_in_Rajasthan.jpg', 'Adventure'),
('Jaisalmer Fort', 'Rajasthan', 'One of the largest fully preserved fortified cities in the world, a "living fort" with shops, hotels, and houses inside.', 'Medium', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/0/05/Jaisalmer_Fort_sunset_view.jpg', 'Adventure'),
('Dudhwa National Park', 'Uttar Pradesh', 'A national park and tiger reserve in the Terai belt of Uttar Pradesh, home to a diverse variety of wildlife.', 'Medium', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Dudhwa_National_Park_Wildlife.jpg', 'Adventure'),
('Ziro Valley', 'Arunachal Pradesh', 'A beautiful valley known for its serene environment, pine-clad hills, and the unique culture of the Apatani tribe.', 'High', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Ziro_Valley_Arunachal_Pradesh.jpg', 'Adventure');

-- More Historical
INSERT INTO tourist_places (name, state, description, budget, safety_level, population_crowd, image_url, type) VALUES
('Charminar', 'Telangana', 'A monument and mosque in Hyderabad, a global symbol of the city, known for its intricate architectural design.', 'Low', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Charminar_in_Hyderabad_India.jpg', 'Historical'),
('Jantar Mantar, Jaipur', 'Rajasthan', 'An 18th-century astronomical observatory and a UNESCO World Heritage site, with the world''s largest stone sundial.', 'Low', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/3/36/Jantar_Mantar_Delhi.jpg', 'Historical'),
('Hampi', 'Karnataka', 'A UNESCO World Heritage Site with a collection of ancient temples, monuments, and ruins of the Vijayanagara Empire.', 'Medium', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Hampi_Virupaksha_temple_main_gopuram.jpg', 'Historical'),
('Ganges River', 'Uttar Pradesh', 'A sacred river in Hinduism, revered as a living goddess. The ghats of Varanasi are a key pilgrimage site.', 'Low', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/1/18/Ganges_River_Varanasi.jpg', 'Historical'),
('Thanjavur', 'Tamil Nadu', 'A city famous for the Brihadishvara Temple and a hub of classical Carnatic music.', 'Low', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/b/b6/Tanjore_Periya_Kovil_in_Thanjavur%2C_Tamil_Nadu.jpg', 'Historical'),
('Madurai', 'Tamil Nadu', 'One of the oldest continuously inhabited cities in the world, home to the Meenakshi Amman Temple.', 'Low', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/7/72/Madurai_city_view.jpg', 'Historical'),
('Hampi Bazar', 'Karnataka', 'A historical street market near the Virupaksha Temple ruins, known for its vibrant local culture.', 'Low', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/a/ab/Hampi_Bazar_Karnataka.jpg', 'Historical'),
('Badami Fort', 'Karnataka', 'A fort complex with historic monuments and beautiful rock carvings.', 'Low', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Badami_Cave_Temples_Karnataka.jpg', 'Historical'),
('City Palace, Jaipur', 'Rajasthan', 'A magnificent palace complex in Jaipur, blending Rajasthani and Mughal architecture, housing museums and grand courtyards.', 'Medium', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/City_Palace_in_Jaipur_India_04-2016_img1.jpg', 'Historical'),
('Udaipur City Palace', 'Rajasthan', 'A royal palace complex situated on the banks of Lake Pichola, known for its intricate carvings and stunning views.', 'Medium', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/6/6a/Udaipur_City_Palace_%285%29.jpg', 'Historical'),
('Jaisalmer Fort', 'Rajasthan', 'One of the largest fully preserved fortified cities in the world, a "living fort" with shops, hotels, and houses inside.', 'Medium', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/0/05/Jaisalmer_Fort_sunset_view.jpg', 'Historical'),
('Mehrangarh Fort', 'Rajasthan', 'One of the largest and most magnificent forts in India, located on a hill in Jodhpur, offering panoramic city views.', 'Low', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Mehrangarh_Fort_in_Jodhpur_India_03-2016_img1.jpg', 'Historical'),
('Mahabalipuram', 'Tamil Nadu', 'A UNESCO World Heritage Site known for its 7th and 8th-century rock-cut temples, mandapas, and shore temples.', 'Low', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Shore_Temple%2C_Mahabalipuram%2C_Tamil_Nadu%2C_India.jpg', 'Historical');

-- More Natural
INSERT INTO tourist_places (name, state, description, budget, safety_level, population_crowd, image_url, type) VALUES
('Pondicherry', 'Puducherry', 'A former French colony known for its colorful streets, Aurobindo Ashram, and tranquil beaches.', 'Low', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/3/35/Pondicherry_Beach.jpg', 'Natural'),
('Munnar', 'Kerala', 'A hill station in the Idukki district, known for its extensive tea plantations, winding lanes, and misty mountains.', 'Medium', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/b/be/Munnar_Tea_Plantations.jpg', 'Natural'),
('Kashmir Valley', 'Jammu and Kashmir', 'Known as "Paradise on Earth," famous for its beautiful lakes, houseboats, and snow-capped mountains.', 'Medium', 'Medium', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Kashmir_Valley.jpg', 'Natural'),
('Mount Abu', 'Rajasthan', 'A hill station in the Aravalli Range, famous for its Dilwara Jain Temples and stunning sunsets.', 'Low', 'High', 'Medium', 'https://upload.wikimedia.org/wikipedia/commons/1/14/Mount_Abu_Rajasthan.jpg', 'Natural'),
('Nilgiri Hills', 'Tamil Nadu', 'A mountain range in the Western Ghats, home to Ooty and Coonoor, known for its tea plantations and scenic beauty.', 'Medium', 'High', 'High', 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Nilgiri_Hills_Tamil_Nadu.jpg', 'Natural'),
('Nanda Devi National Park', 'Uttarakhand', 'A UNESCO World Heritage Site known for its scenic beauty, alpine meadows, and diverse wildlife.', 'High', 'Low', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Nanda_Devi_National_Park_Uttarakhand.jpg', 'Natural'),
('Ziro Valley', 'Arunachal Pradesh', 'A beautiful valley known for its serene environment, pine-clad hills, and the unique culture of the Apatani tribe.', 'High', 'High', 'Low', 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Ziro_Valley_Arunachal_Pradesh.jpg', 'Natural');